name: Test

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: poetry install --no-root
    - name: Test with pytest
      run: make test
