name: Test

on: [push]

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Check out repository
        uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v10.0.1
      - name: Setup environment
        run: make .venv
      - name: Run ty check
        run: make ty
      - name: Run vulture
        run: make vulture
      - name: Run tests
        run: |
          make coverage.xml
          uv run coverage report --format=markdown >> $GITHUB_STEP_SUMMARY
